"""Add status field to Red_Flags

Revision ID: 23c0f106a618
Revises: 563ae4a9017b
Create Date: 2025-02-21 00:42:21.157708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c0f106a618'
down_revision = '563ae4a9017b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red__flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('red__flags', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
